name: (Bad example) env usage with workflow_call

on:
  push:
    branches:
      - "main"

# You can't reference this in any jobs with uses/id in key.
# The env context syntax allows you to use the value of an environment variable
# in your workflow file. You can use the env context in the value of any key in a step except for the id and uses keys. For more information on the step syntax, see "Workflow syntax for GitHub Actions."
#
# https://docs.github.com/en/actions/learn-github-actions/contexts#env-context
env:
  AWS_ENV: dev-private
  AWS_REGION: us-west-3

jobs:
  bad-path:
    runs-on: ubuntu-latest
    steps:
      - name: Try print env
        run: |
          echo ENV: $AWS_ENV
          echo REGION: $AWS_REGION

  start-template-a:
    name: Starting Template A Job
    uses: ./.github/workflows/template-a.yaml
    with:
      state: start
      message: |-
        *ENV*: $AWS_ENV

  start-template-b:
    name: Starting Template B Job
    uses: ./.github/workflows/template-b.yaml
    with:
      aws_env: $AWS_ENV
      aws_region: $AWS_REGION
    secrets:
      TEXT: ${{ secrets.TEXT }}

  start-template-a-2:
    name: Starting Template A Job
    uses: ./.github/workflows/template-a.yaml
    with:
      state: end
      message: |
        *REGION*: $AWS_REGION
