name: Template A
on:
  workflow_call:
    inputs:
      state:
        required: true
        type: string
      message:
        required: true
        type: string

jobs:
  do-something:
    name: Doing something...
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo state - ${{ inputs.state }}
          echo message - ${{ inputs.message }}
